
name: Main Branch CI
run-name: Suite Execution for commit
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
 

jobs:
  build:
    name: Test suite execution
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: ping -c 5 google.com
    - run: npx playwright install-deps
    - name : Installing Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
    - run: pip install virtualenv
    - run: python -m venv venv
    - run: source ./venv/bin/activate
    - run: pip install -r requirements.txt
    - run: rfbrowser init  
    - run: rm -rf results/ | robot tests/
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      if: always()
      with:
          name: regression-artifact
          path: results/
          retention-days: 1
